# Generated by Django 4.0.2 on 2022-03-06 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='family',
            name='name',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.CreateModel(
            name='Evolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_evolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nextevo', to='monsters.monster')),
                ('pre_evolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preevo', to='monsters.monster')),
            ],
        ),
        migrations.CreateModel(
            name='Effectiveness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(choices=[(1.0, 'Neutral'), (2.0, 'Weak'), (0.5, 'Resist'), (0.0, 'Immune')], default=1.0)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monsters.element')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monsters.family')),
            ],
        ),
    ]
