# Generated by Django 4.0.2 on 2022-03-09 00:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0002_element_skill_alter_family_name_alter_monster_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='agility',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='monster',
            name='defense',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='monster',
            name='dexterity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='monster',
            name='hp',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='monster',
            name='intellect',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='monster',
            name='strength',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(1)]),
        ),
    ]
